### ISSUE TITLE
Support more search engines than Yahoo! BOSS for copyvio checking

### ISSUE THREAD

**Issue by earwig** [earwig/earwigbot#19]
Currently, Yahoo! BOSS is the only supported search engine in `earwigbot.wiki.copyvios.search`. Since this engine is proprietary and the WMF might not support it forever, support for other search engines should be implemented.

**Comment by earwig** [comment]
Bing: 977b587e5ec46374993b1090f36eed94d36cf6ef

**Comment by legoktm** [comment]
Bing'd!
